### ISSUE TITLE
Invalid code in dynamic loading example

### ISSUE THREAD

**Issue by thheller** [shadow-cljs/shadow-cljs.org#1]
```clojure
(ns app.extra)

(defn async-code! []
  (println "async code!"))

; another file

(ns app.main
  (:require [shadow.loader :as loader]
            [app.extra :as extra]))

(defn on-load []
  (extra/async-code!))

(defn main! []
  (loader/with-module "extra" on-load))
```

The `app.main` ns can't depend on `app.extra` as that will cause the code to be included in the module that `app.main` is in. You would be getting a warning that `app.extra` was moved into the `app.main` ns.

One option is to use `js/` to call the code directly without `:require`. Another is to use the `resolve` macro. `js/` calls must be manually munged.

```clojure
(defn on-load []
  (js/app.extra.async_code_BANG_))
```

```clojure
(defn on-load []
   ((resolve 'app.extra/async-code!)))
```

**Comment by chenyong** [comment]
Original example is https://github.com/minimal-xyz/minimal-shadow-cljs-loader/tree/master/src/app

I thought it worked when I first added that. Will try again and update the snippet...

**Comment by chenyong** [comment]
clojure

**Comment by thheller** [comment]
The code works yes. The issue is subtle. You'll basically get an empty `extra.js` since the code was already included in the `main.js` due to the `:require`.

There used to be a warning but I just tested it and that seems to broken currently.

**Comment by tiye** [comment]
Made some updates:

* https://github.com/minimal-xyz/minimal-shadow-cljs-loader/commit/2eafbb7ec5573c74383045eed5b330519180d093?diff=split
* https://github.com/shadow-cljs/shadow-cljs.org/commit/2cfe82494c920cb33ff95c6009c2681623499a76

**Comment by thheller** [comment]
The snippet still has a small error.

```
(defn on-load []
  ((resolve 'extra/async-code!))
```

should be `app.extra/async-code!`.

**Comment by chenyong** [comment]
Turned out it's correct in minimal example but I got typo after pasting to home page.

Fixed http://shadow-cljs.org/ .
